### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by jucarope3** [KBlixt/Emhanced#1]
Reading nfo files, this could take a few minutes.
Traceback (most recent call last):
  File "emhanced.py", line 35, in <module>
    config.getfloat('DAY_LIMIT', 14)))
  File "/Users/MiniMac/Downloads/Emhanced-master/recentaddedmod.py", line 63, in recent_releases
    most_recent_date = items[0]['releasedate']
IndexError: list index out of range

**Comment by jucarope3** [comment]
love the idea of your script but can't make it work.... any idea of what mean this?

**Comment by KBlixt** [comment]
I'll take a look into it this weekend.

**Comment by KBlixt** [comment]
I'm sorry for the late response.

I'm not sure what the issue was but I added some more logging in hope to figure out the issue. If your still interested in the script run update it and report back what the script prints.
